reorg

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,6 +5,44 @@ on:
   workflow_dispatch:
 
 jobs:
+  tests:
+    needs: build
+    name: integration tests
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v4
+
+    - name: Set up Go 1.x
+      uses: actions/setup-go@v5
+      with:
+        go-version: ^1.23.6
+
+    - name: Get grip version from go.mod
+      id: get_grip_version
+      run: |
+        GRIP_VERSION=$(grep "github.com/bmeg/grip " go.mod | awk '{print $2}')
+        echo "GRIP_VERSION=${GRIP_VERSION}" >> $GITHUB_ENV
+
+    - name: Install grip from branch
+      run: |
+        go install github.com/bmeg/grip@${{ env.GRIP_VERSION }}
+        if [ ! -f ~/go/bin/grip ]; then
+          echo "Error: grip binary not found at ~/go/bin/grip" >&2
+          exit 1
+        fi
+
+    - name: Make plugins
+      run: make all
+
+    - name: GRIDs Test
+      run: |
+        ~/go/bin/grip server -w writer=gen3_writer.so -w reader=grip-js.so -w graphql=gql-gen.so \
+          -l reader:config=./grip-js/config/gen3.js -l reader:graph=TEST -l \
+          writer:test=true -l graphql:test=true -l reader:auth=true &
+        sleep 5
+        go test -v ./tests/integration
+
   build:
     runs-on: ubuntu-latest
 
@@ -37,58 +75,3 @@ jobs:
 
         # Push the tagged image to Quay.io
         docker push --all-tags $REPO
-
-
-  tests:
-    needs: build
-    name: integration tests
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check out code
-      uses: actions/checkout@v4
-
-    - name: Set up Go 1.x
-      uses: actions/setup-go@v5
-      with:
-        go-version: ^1.23.6
-
-    - name: Get grip version from go.mod
-      id: get_grip_version
-      run: |
-        GRIP_VERSION=$(grep "github.com/bmeg/grip " go.mod | awk '{print $2}')
-        echo "GRIP_VERSION=${GRIP_VERSION}" >> $GITHUB_ENV
-
-    - name: Install grip from branch
-      run: |
-        go install github.com/bmeg/grip@${{ env.GRIP_VERSION }}
-        if [ ! -f ~/go/bin/grip ]; then
-          echo "Error: grip binary not found at ~/go/bin/grip" >&2
-          exit 1
-        fi
-
-    - name: Store grip
-      uses: actions/upload-artifact@v4
-      with:
-        name: gripBin
-        path: ~/go/bin/grip
-      continue-on-error: false
-
-    - name: Make plugins
-      run: make all
-
-    - name: Download grip
-      uses: actions/download-artifact@v4
-      with:
-        name: gripBin
-        path: .
-
-    - name: Make grip executable
-      run: chmod +x ./grip
-
-    - name: GRIDs Test
-      run: |
-        ./grip server -w writer=gen3_writer.so -w reader=grip-js.so -w graphql=gql-gen.so \
-          -l reader:config=./config/gen3.js -l reader:graph=TEST -l \
-          writer:test=true -l graphql:test=true -l reader:auth=true &
-        sleep 5
-        go test -v ./tests/integration
